#!/usr/bin/env python3

import glob
import json
import os
from html.parser import HTMLParser
from genericpath import isdir

languages = {
    "c_and_cplus": [".cpp", ".c++", ".cxx", ".hpp", ".hh", ".h++", ".hxx", ".c," ".cc", ".h"],
    "csharp": [".sln", ".csproj", ".cs", ".cshtml", ".xaml"],
    "golang": [".go"],
    "java": [".java"],
    "javascript": [".js", ".jsx", ".mjs", ".es", ".es6", ".vue", ".hbs", ".ejs", ".njk", ".json", ".raml"],
    "javascript_html": [".htm", ".html", ".xhtm", ".xhtml", ".xml"],
    "python_lang": [".py"],
    "ruby": [".rb", ".erb", ".gemspec", "Gemfile"],
    "typescript": [".ts", ".tsx", ".mts", ".cts"],
}

outlines = dict()
outlines["include"] = set()

class myhtmlparser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.reset()
        self.NEWTAGS = []
        self.NEWATTRS = []
        self.HTMLDATA = []
    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.NEWTAGS.append(tag)
        self.NEWATTRS.append(attrs)
    def handle_data(self, data: str) -> None:
        self.HTMLDATA.append(data)
    def clean(self) -> None:
        self.NEWTAGS = []
        self.NEWATTRS = []
        self.HTMLDATA = []

def serialize_sets(obj):
    if isinstance(obj, set):
        l = list()
        for item in obj:
            if isinstance(item, tuple):
                l.append(dict((x, y) for x, y in item))
        return l

def find_in_list(list, string):
    for item in list:
        if string.strip().endswith(item):
            return True
    return False

def check_html_for_js(file):
    parser = myhtmlparser()
    buf = open(file, "r").read()
    parser.feed(buf)
    for i in range(len(parser.NEWTAGS)):
        if parser.NEWTAGS[i] == "script":
            for j in range(len(parser.NEWATTRS[i])):
                if parser.NEWATTRS[i][j][0] == "type":
                    if find_in_list(languages["javascript"], parser.NEWATTRS[i][j][1]):
                        return True
    return False

for line in glob.glob('**', recursive=True):
    path = line.split('/')[0]
    for lang, extensions in languages.items():
        if find_in_list(extensions, line) and os.path.isdir(path):
            if lang == "javascript_html" and check_html_for_js(path):
                outlines["include"].add(tuple(dict({"target-dir": path, "languages": "javascript-typescript"}).items()))
            else:
                outlines["include"].add(tuple(dict({"target-dir": path, "languages": lang}).items()))

print(json.dumps(outlines, default=serialize_sets))